name: build release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: 🐳 Build & push image
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    env:
      IMAGE_NAME: cron-as-a-service-api
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: install semantic exec
        run: npm install @semantic-release/exec -D

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.NEXUS_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NEXUS_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.NEXUS_CONTAINER_REGISTRY_PASSWORD }}

      - name: Semantic Release github
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.ONSTYR_GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.NEXUS_CONTAINER_REGISTRY_URL }}/docker-hosted/${{ env.IMAGE_NAME }}:${{ steps.semantic-release.outputs.new_release_version }}
            ${{ secrets.NEXUS_CONTAINER_REGISTRY_URL }}/docker-hosted/${{ env.IMAGE_NAME }}:latest